import type { WorkspaceSnapshot } from "./types";

/**
 * Demo workspace snapshot used as a fallback when the database is empty or
 * unreachable. The shape mirrors the OpenProject-style domain: a parent
 * project with a sub-project, work packages of multiple types, and a
 * per-project module configuration.
 */
export const sampleWorkspace: WorkspaceSnapshot = {
  users: [
    {
      id: "u-admin",
      name: "平台管理员",
      role: "admin",
      roles: ["admin"],
      personId: "p1",
      managedProjectIds: ["proj-platform", "proj-ai-pm", "proj-ai-pm-mobile"],
      participatingProjectIds: ["proj-platform", "proj-ai-pm", "proj-ai-pm-mobile"]
    },
    {
      id: "u-pm",
      name: "项目经理",
      role: "projectManager",
      roles: ["projectManager"],
      personId: "p1",
      managedProjectIds: ["proj-ai-pm", "proj-ai-pm-mobile"],
      participatingProjectIds: ["proj-ai-pm", "proj-ai-pm-mobile"]
    },
    {
      id: "u-teamlead",
      name: "团队负责人",
      role: "teamLead",
      roles: ["teamLead"],
      personId: "p3",
      managedProjectIds: [],
      participatingProjectIds: ["proj-ai-pm"]
    },
    {
      id: "u-member",
      name: "项目参与员",
      role: "participant",
      roles: ["participant"],
      personId: "p2",
      managedProjectIds: [],
      participatingProjectIds: ["proj-ai-pm"]
    }
  ],
  people: [
    { id: "p1", name: "产品负责人", role: "Product", capacity: 32, skills: ["产品定义", "用户故事", "验收口径"] },
    { id: "p2", name: "前端开发", role: "Frontend", capacity: 36, skills: ["看板设计", "前端实现", "图表可视化"] },
    { id: "p3", name: "后端开发", role: "Backend", capacity: 36, skills: ["接口设计", "数据建模", "Agent 编排"] },
    { id: "p4", name: "测试与部署", role: "QA/Ops", capacity: 28, skills: ["测试设计", "部署运维", "健康检查"] }
  ],
  projects: [
    {
      id: "proj-platform",
      identifier: "platform",
      name: "平台总览",
      description: "组合 AI 项目管理平台与其子项目的根项目，承载跨项目报表和成员管理。",
      status: "active",
      health: "Low",
      initialDifficulty: "low",
      progress: 35,
      startDate: "2026-01-01T00:00:00.000Z",
      endDate: "2026-12-31T00:00:00.000Z",
      enabledModules: ["overview", "members", "settings"]
    },
    {
      id: "proj-ai-pm",
      identifier: "ai-pm",
      name: "AI 项目管理平台",
      description: "通过对话、动态看板和 AI 管家完成项目任务管理、进度跟进与风险分析。",
      parentId: "proj-platform",
      status: "active",
      health: "Medium",
      initialDifficulty: "medium",
      progress: 42,
      startDate: "2026-01-05T00:00:00.000Z",
      endDate: "2026-06-30T00:00:00.000Z",
      enabledModules: [
        "overview",
        "work_packages",
        "boards",
        "gantt",
        "members",
        "ai_diagnosis",
        "ai_breakdown",
        "settings"
      ]
    },
    {
      id: "proj-ai-pm-mobile",
      identifier: "ai-pm-mobile",
      name: "移动端体验",
      description: "AI 项目管理平台的移动端体验子项目，复用平台核心数据。",
      parentId: "proj-ai-pm",
      status: "onHold",
      health: "Low",
      initialDifficulty: "low",
      progress: 12,
      startDate: "2026-04-01T00:00:00.000Z",
      endDate: "2026-09-30T00:00:00.000Z",
      enabledModules: ["overview", "work_packages", "boards", "members", "settings"]
    }
  ],
  workPackages: [
    {
      id: 1,
      projectId: "proj-ai-pm",
      parentId: 9,
      type: "milestone",
      subject: "Agent OS 里程碑",
      description: "沉淀产品、需求、开发、测试、部署的无人值守流程基线。",
      assigneeId: "p1",
      status: "done",
      priority: "P0",
      origin: "manager",
      createdByUserId: "u-pm",
      percentComplete: 100,
      lastProgressNote: "Agent OS 已交付。",
      dependencies: [],
      isOnCriticalPath: true,
      lastUpdatedAt: "2026-04-25T09:00:00.000Z",
      startDate: "2026-04-20T00:00:00.000Z",
      dueDate: "2026-04-26T00:00:00.000Z",
      requiredSkills: ["产品定义"]
    },
    {
      id: 2,
      projectId: "proj-ai-pm",
      parentId: 9,
      type: "task",
      subject: "实现对话式任务拆解",
      description: "用户输入自然语言后，生成 WorkPackage 草稿和风险候选。",
      assigneeId: "p3",
      status: "inProgress",
      priority: "P0",
      origin: "manager",
      createdByUserId: "u-pm",
      estimateHours: 14,
      percentComplete: 65,
      lastProgressNote: "对话拆解可生成草稿，等待接入服务端权限范围。",
      dependencies: [1],
      isOnCriticalPath: true,
      lastUpdatedAt: "2026-04-26T09:00:00.000Z",
      startDate: "2026-04-26T00:00:00.000Z",
      dueDate: "2026-05-05T00:00:00.000Z",
      requiredSkills: ["接口设计", "Agent 编排"]
    },
    {
      id: 3,
      projectId: "proj-ai-pm",
      parentId: 9,
      type: "task",
      subject: "构建 OpenProject 风格工作项表格与详情面板",
      description: "Primer 风格的 split-screen 工作项视图：表格 + 右侧详情。",
      assigneeId: "p2",
      status: "review",
      priority: "P1",
      origin: "manager",
      createdByUserId: "u-pm",
      estimateHours: 18,
      percentComplete: 80,
      lastProgressNote: "表格与详情面板初版完成，等待 UI 复审。",
      dependencies: [2],
      isOnCriticalPath: false,
      lastUpdatedAt: "2026-04-23T09:00:00.000Z",
      startDate: "2026-04-24T00:00:00.000Z",
      dueDate: "2026-04-30T00:00:00.000Z",
      requiredSkills: ["看板设计", "前端实现"]
    },
    {
      id: 4,
      projectId: "proj-ai-pm",
      parentId: 9,
      type: "task",
      subject: "Docker 与 VPS 部署模板",
      description: "构建 Dockerfile、docker-compose、GitHub Actions 与健康检查。",
      assigneeId: "p4",
      status: "blocked",
      priority: "P1",
      origin: "manager",
      createdByUserId: "u-pm",
      estimateHours: 10,
      percentComplete: 25,
      lastProgressNote: "部署模板存在，等待 VPS 凭据。",
      dependencies: [2, 3],
      isOnCriticalPath: true,
      lastUpdatedAt: "2026-04-20T09:00:00.000Z",
      startDate: "2026-04-27T00:00:00.000Z",
      dueDate: "2026-04-29T00:00:00.000Z",
      requiredSkills: ["部署运维", "健康检查"]
    },
    {
      id: 5,
      projectId: "proj-ai-pm",
      parentId: 9,
      type: "risk",
      subject: "部署凭据未配置",
      description: "无法完成真实 VPS 自动部署，只能交付部署模板。",
      assigneeId: "p4",
      status: "todo",
      priority: "P1",
      origin: "manager",
      createdByUserId: "u-pm",
      percentComplete: 0,
      lastProgressNote: "等待运维提供 SSH key。",
      dependencies: [],
      isOnCriticalPath: false,
      startDate: "2026-04-25T00:00:00.000Z",
      riskLevel: "Medium",
      riskImpact: "无法完成真实 VPS 自动部署，只能交付部署模板。",
      riskMitigation: "使用 GitHub Secrets 占位，并在 README 中说明所需变量。"
    },
    {
      id: 6,
      projectId: "proj-ai-pm",
      parentId: 9,
      type: "risk",
      subject: "真实 LLM Provider 未接入",
      description: "AI 分析暂由 Mock Provider 保障演示。",
      assigneeId: "p3",
      status: "inProgress",
      priority: "P2",
      origin: "manager",
      createdByUserId: "u-pm",
      percentComplete: 30,
      lastProgressNote: "OpenAI Provider 接口已就绪，待接入 API Key。",
      dependencies: [],
      isOnCriticalPath: false,
      startDate: "2026-04-28T00:00:00.000Z",
      riskLevel: "Low",
      riskImpact: "AI 分析暂由 Mock Provider 保障演示。",
      riskMitigation: "保留 OpenAI 兼容 Provider 接口，后续配置 API Key 即可启用。"
    },
    {
      id: 7,
      projectId: "proj-ai-pm-mobile",
      type: "task",
      subject: "移动端工作项列表",
      description: "为移动端实现 OpenProject 风格的工作项列表视图。",
      assigneeId: "p2",
      status: "todo",
      priority: "P2",
      origin: "manager",
      createdByUserId: "u-pm",
      estimateHours: 12,
      percentComplete: 0,
      lastProgressNote: "等待移动端原型设计。",
      dependencies: [3],
      isOnCriticalPath: false,
      startDate: "2026-05-20T00:00:00.000Z",
      dueDate: "2026-06-01T00:00:00.000Z",
      requiredSkills: ["前端实现"]
    },
    {
      id: 8,
      type: "task",
      subject: "整理个人本周待办",
      description: "不绑定项目的个人事项，用于验证我的工作台可见性。",
      assigneeId: "p2",
      status: "todo",
      priority: "P2",
      origin: "self",
      createdByUserId: "u-member",
      estimateHours: 2,
      percentComplete: 0,
      lastProgressNote: "等待开始。",
      dependencies: [],
      isOnCriticalPath: false,
      dueDate: "2026-05-03T00:00:00.000Z",
      requiredSkills: ["个人计划"]
    },
    {
      id: 9,
      projectId: "proj-ai-pm",
      type: "phase",
      subject: "Phase 1 核心能力闭环",
      description: "关键问题：需求稳定性、核心页面验收、测试覆盖。",
      assigneeId: "p1",
      status: "inProgress",
      priority: "P0",
      origin: "manager",
      createdByUserId: "u-pm",
      estimateHours: 40,
      percentComplete: 62,
      lastProgressNote: "首屏、个人工作台、总览基础已进入联调。",
      dependencies: [1],
      isOnCriticalPath: true,
      startDate: "2026-04-20T00:00:00.000Z",
      dueDate: "2026-05-15T00:00:00.000Z",
      requiredSkills: ["产品定义", "接口设计"]
    },
    {
      id: 10,
      projectId: "proj-ai-pm",
      parentId: 9,
      type: "milestone",
      subject: "M2 平台总览验收",
      description: "平台总览与启动页进入演示验收。",
      assigneeId: "p1",
      status: "todo",
      priority: "P0",
      origin: "manager",
      createdByUserId: "u-pm",
      estimateHours: 4,
      percentComplete: 0,
      lastProgressNote: "等待 UI 验收。",
      dependencies: [2, 3, 9],
      isOnCriticalPath: true,
      startDate: "2026-05-10T00:00:00.000Z",
      dueDate: "2026-05-15T00:00:00.000Z",
      requiredSkills: ["验收口径"]
    },
    {
      id: 11,
      projectId: "proj-ai-pm",
      type: "phase",
      subject: "Phase 2 AI 工具与大屏治理",
      description: "关键问题：权限收敛、审计闭环、大屏投屏稳定性。",
      assigneeId: "p1",
      status: "todo",
      priority: "P0",
      origin: "manager",
      createdByUserId: "u-pm",
      estimateHours: 48,
      percentComplete: 35,
      lastProgressNote: "Agent Tools 与大屏展示进入集成验证。",
      dependencies: [9, 10],
      isOnCriticalPath: true,
      startDate: "2026-05-16T00:00:00.000Z",
      dueDate: "2026-06-12T00:00:00.000Z",
      requiredSkills: ["Agent 编排", "可视化"]
    },
    {
      id: 12,
      projectId: "proj-ai-pm",
      parentId: 11,
      type: "task",
      subject: "统一 Tool Registry 调用管道",
      description: "内部 SDK 与 REST 共用统一 schema、权限、审计与幂等逻辑。",
      assigneeId: "p3",
      status: "inProgress",
      priority: "P0",
      origin: "manager",
      createdByUserId: "u-pm",
      estimateHours: 18,
      percentComplete: 55,
      lastProgressNote: "核心注册表已完成，继续补齐审计视图。",
      dependencies: [10],
      isOnCriticalPath: true,
      startDate: "2026-05-16T00:00:00.000Z",
      dueDate: "2026-05-28T00:00:00.000Z",
      requiredSkills: ["Agent 编排", "权限设计"]
    },
    {
      id: 13,
      projectId: "proj-ai-pm",
      parentId: 11,
      type: "task",
      subject: "大屏看板投屏优化",
      description: "适配 1920×1080 / 4K，完成自动刷新、全屏入口和关键路径展示。",
      assigneeId: "p2",
      status: "todo",
      priority: "P1",
      origin: "manager",
      createdByUserId: "u-pm",
      estimateHours: 16,
      percentComplete: 20,
      lastProgressNote: "正在重构按日期驱动的甘特布局。",
      dependencies: [10],
      isOnCriticalPath: false,
      startDate: "2026-05-24T00:00:00.000Z",
      dueDate: "2026-06-08T00:00:00.000Z",
      requiredSkills: ["前端实现", "可视化"]
    },
    {
      id: 14,
      projectId: "proj-ai-pm",
      parentId: 11,
      type: "milestone",
      subject: "M3 Agent Tools 与大屏验收",
      description: "AI 工具管道和展示型大屏完成演示验收。",
      assigneeId: "p1",
      status: "todo",
      priority: "P0",
      origin: "manager",
      createdByUserId: "u-pm",
      estimateHours: 4,
      percentComplete: 0,
      lastProgressNote: "等待 Phase 2 任务完成。",
      dependencies: [12, 13],
      isOnCriticalPath: true,
      startDate: "2026-06-12T00:00:00.000Z",
      dueDate: "2026-06-12T00:00:00.000Z",
      requiredSkills: ["验收口径"]
    },
    {
      id: 15,
      projectId: "proj-ai-pm",
      type: "phase",
      subject: "Phase 3 投产准备与治理",
      description: "关键问题：部署健康检查、生产权限、风险复盘。",
      assigneeId: "p1",
      status: "todo",
      priority: "P1",
      origin: "manager",
      createdByUserId: "u-pm",
      estimateHours: 36,
      percentComplete: 10,
      lastProgressNote: "等待 Phase 2 验收后启动。",
      dependencies: [14],
      isOnCriticalPath: false,
      startDate: "2026-06-13T00:00:00.000Z",
      dueDate: "2026-06-30T00:00:00.000Z",
      requiredSkills: ["部署运维", "治理"]
    },
    {
      id: 16,
      projectId: "proj-ai-pm",
      parentId: 15,
      type: "task",
      subject: "生产部署健康检查",
      description: "完善 Docker、健康检查、回滚说明和上线验收脚本。",
      assigneeId: "p4",
      status: "todo",
      priority: "P1",
      origin: "manager",
      createdByUserId: "u-pm",
      estimateHours: 14,
      percentComplete: 0,
      lastProgressNote: "等待 Agent Tools 验收后开始。",
      dependencies: [14],
      isOnCriticalPath: false,
      startDate: "2026-06-13T00:00:00.000Z",
      dueDate: "2026-06-24T00:00:00.000Z",
      requiredSkills: ["部署运维", "健康检查"]
    },
    {
      id: 17,
      projectId: "proj-ai-pm",
      parentId: 15,
      type: "task",
      subject: "管理员审计与权限复盘",
      description: "检查 API Key、Agent 调用、FeatureFlag 与管理员入口权限。",
      assigneeId: "p1",
      status: "todo",
      priority: "P1",
      origin: "manager",
      createdByUserId: "u-pm",
      estimateHours: 10,
      percentComplete: 0,
      lastProgressNote: "等待投产前统一复核。",
      dependencies: [14],
      isOnCriticalPath: false,
      startDate: "2026-06-20T00:00:00.000Z",
      dueDate: "2026-06-28T00:00:00.000Z",
      requiredSkills: ["权限设计", "审计"]
    },
    {
      id: 18,
      projectId: "proj-ai-pm",
      parentId: 15,
      type: "milestone",
      subject: "M4 投产准备完成",
      description: "投产健康检查、权限复盘和风险闭环完成。",
      assigneeId: "p1",
      status: "todo",
      priority: "P1",
      origin: "manager",
      createdByUserId: "u-pm",
      estimateHours: 4,
      percentComplete: 0,
      lastProgressNote: "等待 Phase 3 完成。",
      dependencies: [16, 17],
      isOnCriticalPath: false,
      startDate: "2026-06-30T00:00:00.000Z",
      dueDate: "2026-06-30T00:00:00.000Z",
      requiredSkills: ["验收口径"]
    },
    {
      id: 21,
      projectId: "proj-ai-pm",
      parentId: 2,
      type: "task",
      subject: "模拟：参与员历史阻塞恢复后继续验证",
      description: "用于验证项目参与员在工作项恢复为进行中后，即使保留历史阻塞和 delay 标签，也可以继续更新进度。",
      assigneeId: "p2",
      status: "inProgress",
      priority: "P1",
      origin: "manager",
      createdByUserId: "u-pm",
      estimateHours: 6,
      percentComplete: 35,
      lastProgressNote: "上游决策已通过，阻塞解除后继续推进联调验证。",
      blockedReason: "等待上一级接口联调决策。",
      blockedStartedAt: "2026-05-08T00:00:00.000Z",
      blockedResolvedAt: "2026-05-15T00:00:00.000Z",
      delayReason: "上游决策等待导致执行窗口延后。",
      delayDays: 3,
      delayStartedAt: "2026-05-10T00:00:00.000Z",
      delayResolvedAt: "2026-05-15T00:00:00.000Z",
      dependencies: [2],
      isOnCriticalPath: false,
      startDate: "2026-05-07T00:00:00.000Z",
      dueDate: "2026-05-10T00:00:00.000Z",
      requiredSkills: ["前端实现", "联调验证"]
    }
  ],
  workPackageComments: [
    {
      id: "wpc-1",
      workPackageId: 2,
      authorPersonId: "p3",
      type: "evidence",
      body: "已完成对话拆解 Mock Provider，下一步需要产品确认真实 LLM 输出字段。",
      createdAt: new Date("2026-04-28T13:00:00.000Z").toISOString(),
      mentionsPersonIds: ["p1"],
      source: "platform"
    },
    {
      id: "wpc-2",
      workPackageId: 3,
      authorPersonId: "p2",
      type: "decision",
      body: "采用 OpenProject 风格的 split-screen 工作项布局，左表右详情。",
      createdAt: new Date("2026-04-28T14:00:00.000Z").toISOString(),
      mentionsPersonIds: ["p1"],
      source: "platform"
    },
    {
      id: "wpc-3",
      workPackageId: 4,
      authorPersonId: "p4",
      type: "blocker",
      body: "VPS SSH 与 GitHub Secrets 尚未配置，部署只能停留在模板验证。",
      createdAt: new Date("2026-04-28T15:00:00.000Z").toISOString(),
      mentionsPersonIds: ["p1", "p3"],
      source: "platform"
    },
    {
      id: "wpc-im-1",
      workPackageId: 3,
      authorPersonId: "p2",
      type: "evidence",
      body: "【飞书回流】#3 已补充表格筛选截图和 hover 效果说明，等待设计复核。",
      createdAt: new Date("2026-04-28T18:00:00.000Z").toISOString(),
      mentionsPersonIds: ["p1"],
      source: "feishu",
      sourceChannelId: "ch-feishu-core",
      externalMessageId: "om_demo_wp3_001",
      externalThreadId: "thread_wp_review",
      authorDisplayName: "前端开发"
    }
  ],
  workPackageApprovals: [
    {
      id: "wpa-1",
      workPackageId: 1,
      reviewerPersonId: "p1",
      status: "approved",
      comment: "Agent OS 里程碑已达成，可关闭。",
      createdAt: new Date("2026-04-28T16:00:00.000Z").toISOString()
    },
    {
      id: "wpa-2",
      workPackageId: 3,
      reviewerPersonId: "p1",
      status: "pending",
      comment: "等待 UI 设计审查后签核。",
      createdAt: new Date("2026-04-28T16:30:00.000Z").toISOString()
    },
    {
      id: "wpa-3",
      workPackageId: 4,
      reviewerPersonId: "p1",
      status: "changesRequested",
      comment: "需要补充部署凭据和回滚说明后再批准。",
      createdAt: new Date("2026-04-28T17:00:00.000Z").toISOString()
    }
  ],
  stewardMessages: [
    {
      id: "sm1",
      type: "progress",
      title: "今日进展",
      body: "AI 项目管理平台已切换到 OpenProject 风格架构，工作项与项目层级开始联动。",
      level: "Low",
      createdAt: new Date("2026-04-28T09:00:00.000Z").toISOString()
    },
    {
      id: "sm2",
      type: "risk",
      title: "部署风险",
      body: "VPS 地址和 SSH 密钥尚未配置，真实自动部署会在 CI 模板完成后等待凭据。",
      level: "Medium",
      createdAt: new Date("2026-04-28T10:00:00.000Z").toISOString()
    }
  ],
  notificationChannels: [
    {
      id: "ch-feishu-core",
      name: "项目飞书群（核心）",
      type: "feishu",
      target: "https://open.feishu.cn/open-apis/bot/v2/hook/demo-token",
      enabled: true,
      audienceRoles: ["admin", "projectManager", "participant"],
      audiencePersonIds: [],
      note: "AI 管家进展、计划提醒推送到此群"
    },
    {
      id: "ch-wecom-risk",
      name: "风险企业微信群",
      type: "wecomBot",
      target: "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=demo-key",
      enabled: true,
      audienceRoles: ["admin", "projectManager"],
      audiencePersonIds: [],
      note: "中等以上风险预警，仅项目经理与管理员可见"
    },
    {
      id: "ch-dingtalk-deploy",
      name: "部署钉钉告警",
      type: "dingtalk",
      target: "https://oapi.dingtalk.com/robot/send?access_token=demo-token",
      enabled: true,
      audienceRoles: ["admin", "projectManager"],
      audiencePersonIds: [],
      secret: "SEC0000000000000000000000000000",
      note: "部署相关告警和健康检查异常"
    },
    {
      id: "ch-slack-overview",
      name: "海外协作 Slack",
      type: "slack",
      target: "https://hooks.slack.com/services/T000/B000/demo-secret",
      enabled: false,
      audienceRoles: ["admin"],
      audiencePersonIds: [],
      note: "保留通道，等待真实凭据后开启"
    },
    {
      id: "ch-email-weekly",
      name: "项目周报邮件组",
      type: "email",
      target: "stakeholders@example.com",
      enabled: true,
      audienceRoles: ["admin", "projectManager"],
      audiencePersonIds: [],
      note: "每周项目进展邮件汇总"
    }
  ],
  notificationRules: [
    {
      id: "rule-progress-feishu",
      name: "项目进展同步",
      eventTypes: ["progress", "planning"],
      minLevel: "Low",
      channelIds: ["ch-feishu-core"],
      audienceRoles: ["admin", "projectManager", "participant"]
    },
    {
      id: "rule-risk-broadcast",
      name: "风险预警广播",
      eventTypes: ["risk"],
      minLevel: "Medium",
      channelIds: ["ch-feishu-core", "ch-wecom-risk"],
      audienceRoles: ["admin", "projectManager"]
    },
    {
      id: "rule-deploy-alert",
      name: "部署告警",
      eventTypes: ["deployment"],
      minLevel: "Low",
      channelIds: ["ch-dingtalk-deploy"],
      audienceRoles: ["admin", "projectManager"]
    },
    {
      id: "rule-weekly-email",
      name: "周报邮件",
      eventTypes: ["progress"],
      minLevel: "Low",
      channelIds: ["ch-email-weekly"],
      audienceRoles: ["admin", "projectManager"]
    }
  ]
};
